services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mottu_mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    ports:
      - "1883:1883"
      - "5050:5050"
  postgres:
    image: postgres:17
    container_name: mottu_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mottu
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/00_schema.sql:ro
  dashboard:
    image: nginx:alpine
    container_name: mottu_dashboard
    restart: unless-stopped
    volumes:
      - ./dashboard:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
volumes:
  pgdata: